language: python

env:
  global:
    - PYTHONPATH=.

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "pip install pipenv"
  - "pipenv install --dev"


script:
  - "pipenv run -- py.test tests -s -v"